### ISSUE TITLE
Mobile_Listing_Tiles

### ISSUE THREAD

**Issue by Raimal** [lazy-suzy/lazysuzy-code#101]
Mobile listing page shows new product rows on user scroll action with 3 items per row even when the page is set to show 2 or 1 item per row. See screenshots below. 

![Screenshot_20190825-231754_Chrome](https://user-images.githubusercontent.com/48194010/63697100-09526d80-c7d1-11e9-8adc-3229ab14dd2b.jpg)
![Screenshot_20190826-071311_Chrome](https://user-images.githubusercontent.com/48194010/63697107-0c4d5e00-c7d1-11e9-9d6e-aba01f5d3ae9.jpg)

**Comment by Aalind01** [comment]
@Raimal please add a link to check
