### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by Raimal** [lazy-suzy/lazysuzy-code#112]
1. Wishlist is not working for Pier1 and Crate&Barrel products. Saving any item from these brands does not save to the wishlist.

2. Items currently in wishlist do not appear as marked in the product listing page. [Update: appearing as marked now, but cannot deselect items to remove them from the wishlist]

3. Remove sort / item count labels if not possible / will take time to make dynamic on the wishlist. 
![image](https://user-images.githubusercontent.com/48194010/64511311-e3c96780-d298-11e9-83ae-dd17d885690e.png)

4. Change wishlist page title from "Products" to "My saved items"

![image](https://user-images.githubusercontent.com/48194010/64511352-fc398200-d298-11e9-94ef-afeb73bbf439.png)

5. WIshlist icon is not visible on product detail page in web and does not work in mobile (not clickable)

6. Selecting item to wishlist while not logged in doesn't prompt user to register or login

7. Items on wishlist page do not appear as marked and can't be unmarked/removed from the wishlist

**Comment by Raimal** [comment]
Thanks. #2 is working now but there doesn't appear to be an option to deselect items / remove items from the wishlist.

**Comment by Raimal** [comment]
#6 is not working in mobile

**Comment by Raimal** [comment]
1. Done

2. Cannot unmark / remove items from wishlist on web or mobile

3. Open

4. Done

5. Open

6. Open

7. Open

**Comment by Aalind01** [comment]
2. is because, the data attribute 'wishlisted' from the wishlist API is passing false on the wishlist page. @AdiUser plz look into this.

**Comment by Raimal** [comment]
To confirm,  2 is related to the listing page  and not the wishlist page

**Comment by Aalind01** [comment]
@Raimal as i said, its backend related. The unmark API is not working correctly. @AdiUser plz look into this asap
