### ISSUE TITLE
Crate&Barrel_API_Mapping

### ISSUE THREAD

**Issue by Raimal** [lazy-suzy/lazysuzy-code#148]
Current price / Sale price is not being captured correctly from Crate & Barrel API.

'is_price' in LazySuzy API should be mapped to 'CurrentPrice' in Crate & Barrel API

See example:

http://lazysuzy.com/mapper/lazysuzy/index.php/test?product=casey-king-black-iron-bed/s128781 
CurrentPrice = 891

https://lazysuzy.com/api/product/128781
is_price = 1049

**Comment by AdiUser** [comment]
![image](https://user-images.githubusercontent.com/18676199/65787777-554d5500-e177-11e9-8f02-875a7ff80cbe.png)
I see the current price value in the lazysuzy API is same as that of our native API. Am I missing something?

**Comment by Raimal** [comment]
This product is no longer on sale so you can't tell from just looking at the API output anymore.
