### ISSUE TITLE
Web_DeptNav

### ISSUE THREAD

**Issue by Raimal** [lazy-suzy/lazysuzy-code#152]
### Department Nav Bar ###

1. Expand the width of the drop down category window so that all categories fit on one line each
2. Left align all Category labels
3. Retain the yellow/gold highlight on the selected Department even after the mouse hovers off, as long as the drop down is active (see screenshot 1 that has highlight and then screenshot 2 does not have highlight
4. Render the same highlight on the selected Category when a user hovers over (remove the underline effect) -- see Sofa in screenshot 2 

**Screenshot 1**
![image](https://user-images.githubusercontent.com/48194010/66173125-8d371b00-e603-11e9-8abe-edf9f4bb85e9.png)

**Screenshot 2**
![image](https://user-images.githubusercontent.com/48194010/66173151-b5bf1500-e603-11e9-9e3a-d2c6db743e56.png)

**Comment by codefromhimanshu** [comment]
Work in progress
