### ISSUE TITLE
Web_Department

### ISSUE THREAD

**Issue by Raimal** [lazy-suzy/lazysuzy-code#153]
For http://staging.lazysuzy.com/products/living - 

1. Reduce image size so full page appears in one screen on 1366x768 resolution

2. Category label font colors should be the standard #0c1c31 color 

3. Also remove the underline effect on hovering over the Category label

4. Add more space between the end of the page and the page footer and also add a background to the footer of #d6d6d6 
 
5. Following category links can be added now: 

- Loveseats & Daybeds: http://staging.lazysuzy.com/products/living/loveseat
- Ottoman, Poufs & Stools: http://staging.lazysuzy.com/products/living/ottomans

6. Keep the Yellow / Gold shading on the Department label (Living) in this case while on the page

**Comment by codefromhimanshu** [comment]
Work in progress
