### ISSUE TITLE
Web_Listing_Image_Bar

### ISSUE THREAD

**Issue by Raimal** [lazy-suzy/lazysuzy-code#73]
Listing price / brand bar not appearing consistently or correctly. See screenshot: only first 3 products have the price bar.

![image](https://user-images.githubusercontent.com/48194010/62828453-75ab5b00-bb9b-11e9-92da-38bb05e6ddf2.png)

**Comment by Aalind01** [comment]
please add a link to replicate.

**Comment by Raimal** [comment]
This issue was fixed already.
