### ISSUE TITLE
Product_Detail_Image_Gallery

### ISSUE THREAD

**Issue by Raimal** [lazy-suzy/lazysuzy-code#78]
West Elm products have a data anomaly whereby the second image in a lot of products is a placeholder .png file path which is creating a white or black image block. This .png file needs to be excluded from the site. 

![image](https://user-images.githubusercontent.com/48194010/62828600-6a5a2e80-bb9f-11e9-8792-08d23f53bb70.png)
![image](https://user-images.githubusercontent.com/48194010/62828615-9970a000-bb9f-11e9-8a3b-02e35c791fde.png)

**Comment by AdiUser** [comment]
@Aalind01 please let me know if you want to handle this one on front-end or should I exclude this image from the data
