### ISSUE TITLE
Web_Product_Detail_Description_LineBreak

### ISSUE THREAD

**Issue by Raimal** [lazy-suzy/lazysuzy-code#79]
Description line breaks are not being reflected on the site. I see them in the database so imagine we should be able to replicate on the site?

![image](https://user-images.githubusercontent.com/48194010/62828638-303d5c80-bba0-11e9-917f-3740c5b56d97.png)
![image](https://user-images.githubusercontent.com/48194010/62828644-4b0fd100-bba0-11e9-8db7-276fac3dfcf4.png)

**Comment by AdiUser** [comment]
![image](https://user-images.githubusercontent.com/18676199/62971178-ca1a3900-be2e-11e9-8226-1e90db61f994.png)

I can change the description data, @Aalind01 will have to handle it differently in the front-end tho
let me know if you guys agree on this format. I'll push the code to DEV then

**Comment by Raimal** [comment]
Looks good to me. @Aalind01 please confirm.
