### ISSUE TITLE
Web_Listing_Rating

### ISSUE THREAD

**Issue by Raimal** [lazy-suzy/lazysuzy-code#88]
Remove space between product name and rating when there is no variation carousel.

![image](https://user-images.githubusercontent.com/48194010/62839090-4566c980-bc3a-11e9-8251-d00614a39ff5.png)

**Comment by Raimal** [comment]
Swatch image is not overlapping with the ratings bar. See screenshot below. Swatch image size should also be reduced to maybe 50% of current size.

![image](https://user-images.githubusercontent.com/48194010/63215785-8189a680-c0e0-11e9-80b3-7986015dfa5c.png)

**Comment by Aalind01** [comment]
swatch image is not fixed for all products. The dimensions are different for different products/brands. For instance, a sofa cant have equal width and height whereas a normal fabric swatch can have equal width and height. So basically, the width will be dynamic for swatch images. We can change the height to a fixed number. Can u give me a specific height number ?

**Comment by Aalind01** [comment]
fixed. now we have fixed height for swatch images.
