### ISSUE TITLE
Product_Variation_Carousel

### ISSUE THREAD

**Issue by Raimal** [lazy-suzy/lazysuzy-code#94]
For WestElm, variations with null value in the swatch_image property should not be displayed in the variation carousel. This situation indicates that either there are no true variations or that the variation is related to size or another attribute which does not have an image component attached to it.

Examples include the following (as shown in the below screenshot):
http://staging.lazysuzy.com/api/variation/product/mid-century-expandable-dining-table-pebble-h3996
http://staging.lazysuzy.com/api/variation/product/mid-century-expandable-dining-table-round-h4230

![image](https://user-images.githubusercontent.com/48194010/63190988-4de54880-c01c-11e9-93f9-531aef8df9ef.png)

**Comment by Aalind01** [comment]
Its not clear. You told previously that when there is no value in the swatch-image, the normal image property should be used. Plz clarify.

**Comment by Raimal** [comment]
Yes that's correct. However, this is causing an issue for West Elm because there are variations that are not associated with images. Pier1 and West Elm will have to be treated differently. For Pier1 there are no swatches so we have to show the product image. And for West Elm when there are no swatches we should not show anything. We can discuss more live.

**Comment by Raimal** [comment]
Screenshots are from: http://staging.lazysuzy.com/products/dining/tables - with West Elm filter for Brand


Image is no longer there, but the image placeholder is still there:

![image](https://user-images.githubusercontent.com/48194010/65051734-72378c00-d91e-11e9-9f1d-3498244f9d3c.png)

It is also still dynamic, see below screenshot if I hover over the box:

![image](https://user-images.githubusercontent.com/48194010/65051933-a612b180-d91e-11e9-8ee8-d9a2ab21ef4e.png)
