### ISSUE TITLE
Mobile_Product_Detail_Icons

### ISSUE THREAD

**Issue by Raimal** [lazy-suzy/lazysuzy-code#96]
Don't show filter icon or ratings icon when they are not present. 
![20190818_195019](https://user-images.githubusercontent.com/48194010/63236217-bfc2bb00-c1f1-11e9-8b52-e0907e9d2970.jpg)

**Comment by Raimal** [comment]
I still see the filter icon.

**Comment by Aalind01** [comment]
Please add a link in comments.

**Comment by Raimal** [comment]
It's there by default on every page. Here's one by random as an example:

http://staging.lazysuzy.com/product/4036408
