### ISSUE TITLE
Product_Price_Format

### ISSUE THREAD

**Issue by Raimal** [lazy-suzy/lazysuzy-code#98]
- [x] 1. Don't show any decimals in the listing page (this will hopefully fix the spacing issue as currently some prices are overflowing to a second line)

- [x] 2. Update font color for the sale price as per the moqup to #b76e79

- [ ] 3. Always show decimals to two points in product detail page where decimals appear. See example - https://www.lazysuzy.com/product/dekalb-leather-grand-sofa-h954?filters=&sort_type=&pageno=0

**Comment by Aalind01** [comment]
1. Should be fixed in the backend.
2. Will be pushed in the next iteration.
