### ISSUE TITLE
Web_Listing_Carousel_Sizing

### ISSUE THREAD

**Issue by Raimal** [lazy-suzy/lazysuzy-code#99]
Confirm sizing and shape of swatches / variation products across all brands. Pier1 image size seems to be good so I would suggest copying those dimensions for the other two brands. Crop West Elm swatches to be a square as well. 

![image](https://user-images.githubusercontent.com/48194010/63357154-cd755f00-c31d-11e9-8926-00446317f062.png)

![image](https://user-images.githubusercontent.com/48194010/63357237-f1d13b80-c31d-11e9-9285-04ee1b402048.png)

![image](https://user-images.githubusercontent.com/48194010/63357347-2513ca80-c31e-11e9-8601-42e8f9ab6a01.png)

**Comment by Aalind01** [comment]
in the backend or frontend ?

**Comment by Aalind01** [comment]
@Raimal Fixed this few days back. plz send a sample link for issues, cant work like this. As fine as i can see, its working fine.
